# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MainInclinometr
                                 A QGIS plugin
 Расчет нклинометрии
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-29
        copyright            : (C) 2026 by GPN-GEO
        email                : jjj@kkk.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MainInclinometr class from file MainInclinometr.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .inclinometr import MainInclinometr
    return MainInclinometr(iface)
