# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MainInclinometrDialog
                                 A QGIS plugin
 Расчет нклинометрии
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-29
        git sha              : $Format:%H$
        copyright            : (C) 2026 by GPN-GEO
        email                : jjj@kkk.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import json

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from qgis.core import (
    QgsMapLayerProxyModel,
    QgsCoordinateTransform,
    QgsProject,
    QgsPointXY
)

# Для функции выбора устья
from qgis.gui import QgsMapToolIdentifyFeature
from qgis.utils import iface
from qgis.PyQt.QtWidgets import QMessageBox

from qgis.PyQt.QtCore import Qt

from qgis.core import QgsVectorLayer, QgsField, QgsFields, QgsProject
from PyQt5.QtCore import QVariant
from qgis.core import QgsFeature, QgsGeometry, QgsPointXY
from .mathematics import Mathematics
from .excel_reader import ExcelReader

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        "inclinometr_dialog_base.ui"
    ),
    from_imports=True,
    import_from="inclinometr"
)


class MainInclinometrDialog(QtWidgets.QDialog, FORM_CLASS):
    def targetLayerChanged(self, layer):

        self.cmbTarget.clear()
    
        if layer is None:
            return
    
        if self.fieldCode == "":
            return
    
        for feature in layer.getFeatures():
    
            if str(feature["oilfield"]) == self.fieldCode:
    
                self.cmbTarget.addItem(
                    str(feature["tid"]),
                    feature.id()
                )
    def __init__(self, parent=None):
        """Constructor."""

        super(MainInclinometrDialog, self).__init__(parent)
        self.math = Mathematics(self)
        self.setupUi(self)
        self.setFixedSize(self.size())        
        
        self.setWindowFlag(Qt.WindowStaysOnTopHint, True)
        self.show()
        

        # %% Вкладка --- Устье ---

        
        # Инструмент выбора
        self.wellHeadIdentifyTool = None
        # Здесь будет храниться выбранное устье
        self.targetIdentifyTool = None
        # Здесь будет храниться выбранное устье
        self.selectedWellHead = None
        # Система координат слоя
        self.crsLayerWellHead = None
        # Выбранная система координат
        self.crsOutputWellHead = None
        
        # Фильтр списка слоев - только слои точек
        self.mMapLayerComboBoxWellHead.setFilters(
            QgsMapLayerProxyModel.PointLayer
        )
        # Обработка события выбора слоя устьев
        self.mMapLayerComboBoxWellHead.layerChanged.connect(
            self.mMapLayerComboBoxWellHeadChanged
        )

        

        # Подключаем кнопку
        self.btnSelectWellHead.clicked.connect(
            self.selectWellHead
        )

        self.mQgsProjectionSelectionWidgetWellHead.crsChanged.connect(
            self.wellHeadCrsChanged
        )
        self.mQgsProjectionSelectionWidgetTarget.crsChanged.connect(
            self.targetCrsChanged
        )

        # %% Вкладка --- Цели ---

        
        self.selectedTarget = None

        # Код месторождения выбранного устья
        self.fieldCode = ""
        
        # Фильтр только точечных слоев
        self.mMapLayerComboBoxTarget.setFilters(
            QgsMapLayerProxyModel.PointLayer
        )
        
        # При смене слоя целей обновляем список целей
        self.mMapLayerComboBoxTarget.layerChanged.connect(
            self.targetLayerChanged
        )
        
        # При выборе цели из списка
        self.cmbTarget.currentIndexChanged.connect(
            self.targetChanged
        )
        

        # %% Вкладка --- Слои

        # исходные слои которые БУДУТ включены в рабочие слои
        self.positionLayers = []
        self.targetLayers = []
        
        # Фильтр только точечных слоев
        self.mMapLayerComboBoxPositions.setFilters(
            QgsMapLayerProxyModel.PointLayer
        )
        
        # Фильтр только точечных слоев
        self.mMapLayerComboBoxTargets.setFilters(
            QgsMapLayerProxyModel.PointLayer
        )
        
        
        # Подключение кнопок для выбора слоев
        self.btnAddPositionLayer.clicked.connect(self.addPositionLayer)
        self.btnRemovePositionLayer.clicked.connect(self.removePositionLayer)
        
        self.btnAddTargetLayer.clicked.connect(self.addTargetLayer)
        self.btnRemoveTargetLayer.clicked.connect(self.removeTargetLayer)
        
        # добавление кнопок создания рабочих слоев
        self.btnCreatePositionsLayer.clicked.connect(self.createPositionsLayer)
        self.btnCreateTargetsLayer.clicked.connect(self.createTargetsLayer)
        
        # Рабочие слои
        self.layerPositions = None
        self.layerTargets = None
        self.layerOilfields = None
        
        self.btnCreateOilFieldsLayer.clicked.connect(self.createOilFieldsLayer)
        
        self.btnSelectTarget.clicked.connect(
            self.selectTarget
        )
        
        # Система координат слоя целей
        self.crsLayerTarget = None
        
        # Система координат вывода целей
        self.crsOutputTarget = None
        
        
        self.mQgsProjectionSelectionWidgetTarget.crsChanged.connect(
            self.targetCrsChanged
        )
        
        
        self.selectedTargets = []
        
        self.excel = ExcelReader(self)


        self.btnLoadInclinometry.clicked.connect(
            self.math.loadInclinometry
        )


        self.btnCalculateInclinometry.clicked.connect(
            self.math.calculateInclinometry
        )
        # %%
    def selectTarget(self):
        """Выбор цели"""
    
        layer = QgsProject.instance().mapLayersByName("Targets_WORK")
    
        if not layer:
            QMessageBox.warning(
                self,
                "Внимание",
                "Не найден слой Targets_WORK."
            )
            return 
        
        self.layerTarget = layer[0]
    
        self.targetIdentifyTool = QgsMapToolIdentifyFeature(
            iface.mapCanvas()
        )
    
        self.targetIdentifyTool.setLayer(self.layerTarget)
    
        self.targetIdentifyTool.featureIdentified.connect(
            self.targetSelected
        )
    
        iface.mapCanvas().setMapTool(
            self.targetIdentifyTool
        )
    def addTargetToTable(self, feature):
    
        row = self.tableTargets.rowCount()
        self.tableTargets.insertRow(row)
    
        # ID цели
        self.tableTargets.setItem(
            row,
            0,
            QtWidgets.QTableWidgetItem(str(feature["tid"]))
        )
    
        # Координаты
        north = feature.geometry().asPoint().y()
        east = feature.geometry().asPoint().x()
    
        transform = QgsCoordinateTransform(
            self.layerTarget.crs(),
            self.crsOutputTarget,
            QgsProject.instance()
        )
    
        targetPoint = transform.transform(
            QgsPointXY(east, north)
        )
    
        if self.crsOutputTarget.isGeographic():
            northText = f"{targetPoint.y():.10f}"
            eastText = f"{targetPoint.x():.10f}"
        else:
            northText = f"{targetPoint.y():.3f}"
            eastText = f"{targetPoint.x():.3f}"
    
        self.tableTargets.setItem(
            row,
            1,
            QtWidgets.QTableWidgetItem(northText)
        )
    
        self.tableTargets.setItem(
            row,
            2,
            QtWidgets.QTableWidgetItem(eastText)
        )
    
        return northText, eastText
    
    
    def targetSelected(self, feature):
    
        # Сохраняем выбранную цель
        self.selectedTargets.append(feature)
    
        # Название цели
        self.txtTargetName.setText(
            str(feature["tid"])
        )
    
        # Определяем СК слоя
        crs = self.layerTarget.crs()
    
        self.crsLayerTarget = crs
        self.crsOutputTarget = crs
    
        self.mQgsProjectionSelectionWidgetTarget.blockSignals(True)
        self.mQgsProjectionSelectionWidgetTarget.setCrs(crs)
        self.mQgsProjectionSelectionWidgetTarget.blockSignals(False)
    
        northText, eastText = self.addTargetToTable(feature)
    
        self.txtTargetNorth.setText(northText)
        self.txtTargetEast.setText(eastText)
    
        iface.mapCanvas().unsetMapTool(
            self.targetIdentifyTool
        )
    def mMapLayerComboBoxWellHeadChanged(self, layer):
        """Метод обработки события выбора слоя устьев"""
        if layer is None:
            self.mQgsProjectionSelectionWidgetWellHead.setEnabled(False)
        else:
            # Здесь можно сделать дополнительную проверку на то,
            # что это децствительно слой устьев или позиций
            
            # Включаем выбор системы координат
            self.mQgsProjectionSelectionWidgetWellHead.setEnabled(True)
            # Получаем систему координат слоя
            crs = layer.crs()
            self.crsLayerWellHead = crs
            self.crsOutputWellHead = crs
            # Устанавливаем ее в виджет
            self.mQgsProjectionSelectionWidgetWellHead.setCrs(crs)
            # Включаем кнопку выбора устья
            self.btnSelectWellHead.setEnabled(True)
   
    # =========================================================
    # %% ФУНКЦИИ УСТЬЯ

    def selectWellHead(self):
        """Выбор устья"""    
        self.selectFeature(
            self.mMapLayerComboBoxWellHead,
            self.wellHeadSelected
        )
        
    def selectFeature(self, layerComboBox, callback):
        """Универсальная функция выбора объекта на карте"""
        layer = layerComboBox.currentLayer()
        self.layerWellHead = layer

        if layer is None:
            QMessageBox.warning(
                self,
                "Внимание",
                "Сначала выберите слой."
            )
            return

        self.wellHeadIdentifyTool = QgsMapToolIdentifyFeature(
            iface.mapCanvas()
        )
        self.wellHeadIdentifyTool.setLayer(layer)
        self.wellHeadIdentifyTool.featureIdentified.connect(
            callback
        )

        iface.mapCanvas().setMapTool(
            self.wellHeadIdentifyTool
        )
        
    def wellHeadSelected(self, feature):
        # Сохраняем выбранный объект
        self.selectedWellHead = feature
        
        plugin_dir = os.path.dirname(__file__)
        settings_path = os.path.join(
            plugin_dir,
            "settings",
            "settings.json"
        )
        
        with open(settings_path, encoding="utf-8") as f:
            settings = json.load(f)
            
    
            # QMessageBox.information(self, "Слой", "Это устья ГеоБД")
            self.txtWellHeadName.setText(
                str(feature[settings["WellHead"]["Layers"]["Position_WORK"]["name"]])
            )
            self.txtWellHeadGround.setText("")
            self.txtWellHeadRotor.setText(
                str(feature[settings["WellHead"]["Layers"]["Position_WORK"]["rotor"]])
            )
            self.txtWellHeadLicense.setText(
                str(feature[settings["WellHead"]["Layers"]["Position_WORK"]["lic"]])
            )
            # Сохраняем код месторождения
            self.fieldCode = str(feature["oilfield"]).split("_")[0]
           
                
            north = feature.geometry().asPoint().y()
            east = feature.geometry().asPoint().x()
            
            crs_l = self.layerWellHead.crs()
            crs_t = self.crsOutputWellHead
            
            # Создаем преобразование координат
            transform = QgsCoordinateTransform(crs_l, crs_t, QgsProject.instance())
            
            # Исходная точка
            sourcePoint = QgsPointXY(east, north)
    
            # Пересчет
            targetPoint = transform.transform(sourcePoint)
            
            if self.crsOutputWellHead.isGeographic():
                self.txtWellHeadNorth.setText(f"{targetPoint.y():.10f}")
                self.txtWellHeadEast.setText(f"{targetPoint.x():.10f}")
            else:
                self.txtWellHeadNorth.setText(f"{targetPoint.y():.3f}")
                self.txtWellHeadEast.setText(f"{targetPoint.x():.3f}")
        
        # # По умолчанию отметка равна 0
        # elevation = 0
        # # Если точка имеет координату Z
        # # if point.is3D():
        # #     elevation = point.z()
        # self.txtWellHeadElevation.setText(f"{elevation:.3f}")
        
        # Выключаем инструмент выбора
        iface.mapCanvas().unsetMapTool(
            self.wellHeadIdentifyTool
        )

    #%% ФУНКЦИЯ СМЕНЫ СК
    
    def wellHeadCrsChanged(self, crs):
        
        self.crsLayerWellHead = self.crsOutputWellHead
        self.crsOutputWellHead = crs
        
        if self.txtWellHeadNorth.text() != '' and self.txtWellHeadEast.text() != '':
            north = float(self.txtWellHeadNorth.text())
            east = float(self.txtWellHeadEast.text())
            
            # Создаем преобразование координат
            transform = QgsCoordinateTransform(
                self.crsLayerWellHead,
                self.crsOutputWellHead,
                QgsProject.instance()
            )
            
            # Исходная точка
            sourcePoint = QgsPointXY(east, north)
    
            # Пересчет
            targetPoint = transform.transform(sourcePoint)
            
            if self.crsOutputWellHead.isGeographic():
                self.txtWellHeadNorth.setText(f"{targetPoint.y():.10f}")
                self.txtWellHeadEast.setText(f"{targetPoint.x():.10f}")
            else:
                self.txtWellHeadNorth.setText(f"{targetPoint.y():.3f}")
                self.txtWellHeadEast.setText(f"{targetPoint.x():.3f}")
            
            # QMessageBox.warning(
            #     self,
            #     "Внимание",
            #     f"Изменилась система координат! {targetPoint.y()} {targetPoint.x()}"
            # )
        
     # Автоматическое заполнение списка целей в зависимости от слоя
    def targetCrsChanged(self, crs):

        self.crsOutputTarget = crs
    
        # очистить таблицу
        self.tableTargets.setRowCount(0)
    
        # заполнить заново
        for feature in self.selectedTargets:
            self.addTargetToTable(feature)
    
        # если выбрана текущая цель — обновить поля справа
        if self.selectedTargets:
            feature = self.selectedTargets[-1]
    
            northText = self.tableTargets.item(
                self.tableTargets.rowCount()-1, 1
            ).text()
    
            eastText = self.tableTargets.item(
                self.tableTargets.rowCount()-1, 2
            ).text()
    
            self.txtTargetNorth.setText(northText)
            self.txtTargetEast.setText(eastText)
    #%% ФУНКЦИИ ДЛЯ СОЗДАНИЯ РАБОЧЕГО СЛОЯ
    #Функции кнопок для создания рабочих слоев
    
    # Функционал кнопки добавления слоя позиции
    def addPositionLayer(self):
        layer = self.mMapLayerComboBoxPositions.currentLayer()
    
        if layer is None:
            return
    
        if layer not in self.positionLayers:
            self.positionLayers.append(layer)
            self.listWidgetPositionLayers.addItem(layer.name())
            
    # Функционал кнопки удаления слоя позиции
    def removePositionLayer(self):
        selected = self.listWidgetPositionLayers.currentRow()
    
        if selected >= 0:
            self.listWidgetPositionLayers.takeItem(selected)
            del self.positionLayers[selected]
      
    # Функционал кнопки Создания рабочего слоя позиций    
    def createPositionsLayer(self):

        # удалить старый рабочий слой если есть
        if self.layerPositions:
            QgsProject.instance().removeMapLayer(self.layerPositions.id())
            self.layerPositions = None
    
        # создать новый слой
        self.layerPositions = QgsVectorLayer(
            "Point?crs=EPSG:4284",
            "Positions_WORK",
            "memory"
        )
        
        # Добавление атрибутов в новый слой
        dp = self.layerPositions.dataProvider()
    
        fields = QgsFields()
        fields.append(QgsField("name", QVariant.String))
        fields.append(QgsField("pos", QVariant.String))
        fields.append(QgsField("ground", QVariant.String))
        fields.append(QgsField("rotor", QVariant.String))
        fields.append(QgsField("tfield", QVariant.String))
        fields.append(QgsField("oilfield", QVariant.String))
        fields.append(QgsField("oilfield_name", QVariant.String))
        fields.append(QgsField("source", QVariant.String))
        dp.addAttributes(fields)
        self.layerPositions.updateFields()
    
        QgsProject.instance().addMapLayer(self.layerPositions)
        self.importPositions()
  
   
    
    # Функции рабочего слоя Позиции
    def getPositionMapping(self, layer):
        """
        Определяет тип слоя (ARMM / GeoBD)
        и возвращает соответствующий mapping из settings.json
        """
    
        plugin_dir = os.path.dirname(__file__)
        settings_path = os.path.join(
            plugin_dir,
            "settings",
            "settings.json"
        )
    
        with open(settings_path, encoding="utf-8") as f:
            settings = json.load(f)
    
        # проверка что слой существует
        if layer is None:
            return None

        # -----------------------------
        # 1. Определяем тип слоя
        # -----------------------------
    
        fields = layer.fields()
    
        # GeoBD признак 
        if fields.indexOf("license_area") != -1:
            return settings["WellHead"]["Layers"]["geobd"]
    
        # иначе считаем ARMM
        else:
            return settings["WellHead"]["Layers"]["armm"]
            
   
    #функция для мапинга с учетом значений none (она сипользуется при маппинге позиций и целей)
    def getMappedValue(self, feature, mapping, key):

        field = mapping.get(key)
    
        if field is None:
            return ""
    
        if field == "none":
            return ""
    
        if feature.fields().indexOf(field) == -1:
            return ""
    
        value = feature[field]
    
        if value is None:
            return ""
    
        return str(value)
    
    # Заполнение рабочего слоя позиций
    def importPositions(self):

        if self.layerPositions is None:
            return
    
        dp = self.layerPositions.dataProvider()
    
        features_to_add = []
    
        for layer in self.positionLayers:
    
            mapping = self.getPositionMapping(layer)
            if mapping is None:
                continue
    
            for feature in layer.getFeatures():

                newFeature = QgsFeature(self.layerPositions.fields())
                newFeature.setGeometry(feature.geometry())
            
            
                newFeature["name"] = self.getMappedValue(feature, mapping, "name")
                newFeature["pos"] = self.getMappedValue(feature, mapping, "pos")
                newFeature["ground"] = self.getMappedValue(feature, mapping, "ground")
                newFeature["rotor"] = self.getMappedValue(feature, mapping, "rotor")
                newFeature["tfield"] = self.getMappedValue(feature, mapping, "lic")
                newFeature["oilfield"] = self.getMappedValue(feature, mapping, "oilfield").split("_")[0]
                newFeature["oilfield_name"] = self.getMappedValue(feature, mapping, "oilfield_name").strip().title()
                newFeature["source"] = layer.name()
            
                features_to_add.append(newFeature)
    
        dp.addFeatures(features_to_add)
        print("Добавлено:", len(features_to_add))
        print("В рабочем слое:", self.layerPositions.featureCount())
    
        self.layerPositions.updateExtents()
        self.layerPositions.triggerRepaint()
            
    #%% Функции рабочего слоя Цели  
    # Функционал кнопки добавления слоя цели
    def addTargetLayer(self):
        layer = self.mMapLayerComboBoxTargets.currentLayer()
    
        if layer is None:
            return
    
        if layer not in self.targetLayers:
            self.targetLayers.append(layer)
            self.listWidgetTargetLayers.addItem(layer.name())
       
    # Функционал кнопки удаления слоя цели
    def removeTargetLayer(self):
        selected = self.listWidgetTargetLayers.currentRow()
    
        if selected >= 0:
            self.listWidgetTargetLayers.takeItem(selected)
            del self.targetLayers[selected]

    
       # Функционал кнопки Создания рабочего слоя целей    
    def createTargetsLayer(self):

        # удалить старый слой если есть
        if self.layerTargets:
            QgsProject.instance().removeMapLayer(self.layerTargets.id())
            self.layerTargets = None
    
        # создать новый слой
        self.layerTargets = QgsVectorLayer(
            "Point?crs=EPSG:4284",
            "Targets_WORK",
            "memory"
        )
    
        dp = self.layerTargets.dataProvider()
    
        fields = QgsFields()
        fields.append(QgsField("tid", QVariant.String))
        fields.append(QgsField("oilfield", QVariant.String))
        fields.append(QgsField("source", QVariant.String))
    
        dp.addAttributes(fields)
        self.layerTargets.updateFields()
    
        QgsProject.instance().addMapLayer(self.layerTargets)
        self.importTargets()              
        

                 
    def targetChanged(self, index):
     
         if index < 0:
             return
     
         layer = self.mMapLayerComboBoxTarget.currentLayer()
     
         if layer is None:
             return
     
         feature_id = self.cmbTarget.currentData()
     
         if feature_id is None:
             return
     
         # Получаем объект по его id
         feature = layer.getFeature(feature_id)
     
         # Сохраняем выбранную цель
         self.selectedTarget = feature
     
         # Пока выводим только название (или идентификатор) цели
         self.txtTargetName.setText(
             self.cmbTarget.currentText()
         )            
    # Заполнение рабочего слоя целей
    def importTargets(self):
    
        if self.layerTargets is None:
            return
            
        plugin_dir = os.path.dirname(__file__)
        settings_path = os.path.join(
            plugin_dir,
            "settings",
            "settings.json"
        )
        
        with open(settings_path, encoding="utf-8") as f:
            settings = json.load(f)
        
        mapping = settings["Target"]["Layers"]["default"]
        dp = self.layerTargets.dataProvider()
    
        features_to_add = []
    
        for layer in self.targetLayers:
    

            if mapping is None:
                continue
    
            for feature in layer.getFeatures():
    
                newFeature = QgsFeature(self.layerTargets.fields())
                newFeature.setGeometry(feature.geometry())
                newFeature["tid"] = self.getMappedValue(feature, mapping, "tid")
                newFeature["oilfield"] = self.getMappedValue(feature, mapping, "oilfield").split("_")[0]
                newFeature["source"] = layer.name()
            
                features_to_add.append(newFeature)
    
        dp.addFeatures(features_to_add)

    
        self.layerTargets.updateExtents()
        self.layerTargets.triggerRepaint()
        
        
    #%% Рабочий слой месторождений
    def createOilFieldsLayer(self):

        # удалить старый слой
        if self.layerOilfields:
            QgsProject.instance().removeMapLayer(self.layerOilfields.id())
            self.layerOilfields = None
    
        # негеометрический memory-слой
        self.layerOilfields = QgsVectorLayer(
            "None",
            "Oilfields_WORK",
            "memory"
        )
    
        dp = self.layerOilfields.dataProvider()
    
        fields = QgsFields()
        fields.append(QgsField("oilfield", QVariant.String))
        fields.append(QgsField("name", QVariant.String))
    
        dp.addAttributes(fields)
        self.layerOilfields.updateFields()
    
        QgsProject.instance().addMapLayer(self.layerOilfields)
    
        self.importOilfields()
        
        
        
        
    def importOilfields(self):
    
        if self.layerOilfields is None:
            return
    
    
        dp = self.layerOilfields.dataProvider()
    
        features_to_add = []
    
        # словарь для удаления дублей
        oilfields = {}
    
    
        # ============================
        # 1. Сначала берем из Positions_WORK
        # ============================
    
        if self.layerPositions is not None:
    
            for feature in self.layerPositions.getFeatures():
    
                code = str(feature["oilfield"])
    
                name = str(feature["oilfield_name"]).upper()
    
    
                if code not in oilfields:
    
                    oilfields[code] = name
    
    
    
        # ============================
        # 2. Добавляем коды из Targets_WORK,
        #    если их еще нет
        # ============================
    
        if self.layerTargets is not None:
    
            for feature in self.layerTargets.getFeatures():
    
                code = str(feature["oilfield"])
    
    
                if code not in oilfields:
    
                    oilfields[code] = ""
    
    
    
        # ============================
        # Запись в OilFields_WORK
        # ============================
    
        for code, name in oilfields.items():
    
            newFeature = QgsFeature(
                self.layerOilfields.fields()
            )
    
    
            newFeature["oilfield"] = code
            newFeature["name"] = name
    
    
            features_to_add.append(newFeature)
    
    
    
        dp.addFeatures(features_to_add)
    
    
        self.layerOilfields.updateExtents()
        self.layerOilfields.triggerRepaint()
        
